name: Deploy to Netlify

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1 # Number of commits to fetch. Useful for cache key generation.
      - name: Build
        run: |
          yarn build

